// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.865
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"github.com/pynezz/pynezz_com/templates/layout"
)

const secStyle = "flex flex-col space-y-3 bg-crust text-teal flex-grow w-full h-full"

func Stats() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		var templ_7745c5c3_Var2 = []any{"section", secStyle}
		templ_7745c5c3_Err = templ.RenderCSSItems(ctx, templ_7745c5c3_Buffer, templ_7745c5c3_Var2...)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<section class=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(templ.CSSClasses(templ_7745c5c3_Var2).String())
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/pages/stats.templ`, Line: 1, Col: 0}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\" data-store=\"{posts: 0, tags: 0, views: 0, visitors: 0, loading: true}\" data-on-load=\"$$get(&#39;/api/stats&#39;)\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var4 = []any{"h1", layout.Title}
		templ_7745c5c3_Err = templ.RenderCSSItems(ctx, templ_7745c5c3_Buffer, templ_7745c5c3_Var4...)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<h1 class=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var5 string
		templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.JoinStringErrs(templ.CSSClasses(templ_7745c5c3_Var4).String())
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/pages/stats.templ`, Line: 1, Col: 0}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var5))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "\">Stats</h1><container class=\"flex flex-col space-y-3\"><p class=\"font-mono font-light italic\">This page (as with every page) is a work in progress. I plan to add more stats in the future.</p><div data-show=\"$loading\" class=\"text-center\"><p class=\"font-mono text-subtext1\">Loading stats...</p></div><div data-show=\"!$loading\" class=\"flex flex-col flex-wrap w-max space-y-2\"><div class=\"flex flex-row justify-between min-w-48\"><p class=\"font-mono\">Total Posts:</p><p class=\"font-semibold\" data-text=\"$posts\"></p></div><div class=\"flex flex-row justify-between\"><p class=\"font-mono whitespace-pre\">Total Tags:</p><p class=\"font-semibold\" data-text=\"$tags\"></p></div><div class=\"flex flex-row justify-between\"><p class=\"font-mono\">Total Views:</p><p class=\"font-semibold\" data-text=\"$views\"></p></div><div class=\"flex flex-row justify-between\"><p class=\"font-mono\">Total Visitors:</p><p class=\"font-semibold\" data-text=\"$visitors\"></p></div><button class=\"mt-4 px-4 py-2 bg-teal text-base rounded hover:bg-sky transition-colors\" data-on-click=\"$$get(&#39;/api/stats&#39;)\">Refresh Stats</button></div></container></section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func stats() templ.ComponentScript {
	return templ.ComponentScript{
		Name: `__templ_stats_464a`,
		Function: `function __templ_stats_464a(){document.addEventListener("DOMContentLoaded", function() {
    document.body.classList.add("bg-crust");
  });
}`,
		Call:       templ.SafeScript(`__templ_stats_464a`),
		CallInline: templ.SafeScriptInline(`__templ_stats_464a`),
	}
}

var _ = templruntime.GeneratedTemplate
