// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.865
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"github.com/pynezz/pynezz_com/templates/layout"
)

const secStyle = "flex flex-col space-y-3"

func Tags(tags map[string]int) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		var templ_7745c5c3_Var2 = []any{"section", secStyle}
		templ_7745c5c3_Err = templ.RenderCSSItems(ctx, templ_7745c5c3_Buffer, templ_7745c5c3_Var2...)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<section class=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(templ.CSSClasses(templ_7745c5c3_Var2).String())
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/tags.templ`, Line: 1, Col: 0}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\" data-store=\"{searchTerm: &#39;&#39;, tags: [], filteredTags: [], loading: true, sortBy: &#39;name&#39;}\" data-computed-filteredTags=\"$tags.filter(tag =&gt; !$searchTerm || tag.name.toLowerCase().includes($searchTerm.toLowerCase())).sort((a, b) =&gt; { if ($sortBy === &#39;name&#39;) return a.name.localeCompare(b.name); return b.count - a.count; })\" data-on-load=\"$$get(&#39;/api/tags&#39;)\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var4 = []any{"h1", layout.Title}
		templ_7745c5c3_Err = templ.RenderCSSItems(ctx, templ_7745c5c3_Buffer, templ_7745c5c3_Var4...)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<h1 class=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var5 string
		templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.JoinStringErrs(templ.CSSClasses(templ_7745c5c3_Var4).String())
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/tags.templ`, Line: 1, Col: 0}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var5))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "\">Tags</h1><!-- Search and Sort Controls --><div class=\"flex flex-col md:flex-row gap-4 mb-6\"><input type=\"text\" placeholder=\"Search tags...\" class=\"flex-1 px-4 py-2 rounded border border-surface0 bg-mantle text-text focus:outline-none focus:border-teal\" data-model=\"searchTerm\"> <select class=\"px-4 py-2 rounded border border-surface0 bg-mantle text-text focus:outline-none focus:border-teal\" data-model=\"sortBy\"><option value=\"name\">Sort by Name</option> <option value=\"count\">Sort by Count</option></select> <button class=\"px-4 py-2 bg-teal text-base rounded hover:bg-sky transition-colors\" data-on-click=\"$$get(&#39;/api/tags&#39;)\">Refresh</button></div><!-- Loading State --><div data-show=\"$loading\" class=\"text-center py-8\"><p class=\"text-subtext1\">Loading tags...</p></div><!-- Tags Display --><div data-show=\"!$loading &amp;&amp; $filteredTags.length &gt; 0\" class=\"flex flex-row flex-wrap gap-2\"><div data-for=\"tag in $filteredTags\" data-key=\"tag.name\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var6 = []any{"a", layout.TagBtn + " bg-mantle hover:bg-surface0 transition-colors"}
		templ_7745c5c3_Err = templ.RenderCSSItems(ctx, templ_7745c5c3_Buffer, templ_7745c5c3_Var6...)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "<a data-attr-href=\"&#39;/tags/&#39; + tag.name\" class=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var7 string
		templ_7745c5c3_Var7, templ_7745c5c3_Err = templ.JoinStringErrs(templ.CSSClasses(templ_7745c5c3_Var6).String())
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/tags.templ`, Line: 1, Col: 0}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var7))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "\"><span data-text=\"tag.name\"></span> <span class=\"text-subtext0 font-mono text-sm\" data-text=\"&#39; | &#39; + tag.count\"></span></a></div></div><!-- No Results --><div data-show=\"!$loading &amp;&amp; $filteredTags.length === 0\" class=\"text-center py-8\"><p class=\"text-subtext1\">No tags found matching your search.</p></div><!-- Stats Summary --><div data-show=\"!$loading\" class=\"mt-6 p-4 bg-mantle rounded-lg\"><p class=\"text-sm text-subtext1\">Showing <span data-text=\"$filteredTags.length\"></span> of <span data-text=\"$tags.length\"></span> tags</p></div></section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
